"""add geocoding_cache

Revision ID: 04efb17a68ec
Revises: bbf394491998
Create Date: 2026-02-18 13:55:24.794822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04efb17a68ec'
down_revision: Union[str, None] = 'bbf394491998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoding_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_query', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_query', 'provider', name='uq_geocoding_cache_query_provider')
    )
    op.create_index(op.f('ix_geocoding_cache_raw_query'), 'geocoding_cache', ['raw_query'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geocoding_cache_raw_query'), table_name='geocoding_cache')
    op.drop_table('geocoding_cache')
    # ### end Alembic commands ###
