"""add_user_embeddings

Revision ID: 33a01e4055a3
Revises: d9130dac8367
Create Date: 2026-02-25 22:42:50.004930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '33a01e4055a3'
down_revision: Union[str, None] = 'd9130dac8367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_embeddings_user_id')
    )
    op.create_index(op.f('ix_user_embeddings_id'), 'user_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_user_embeddings_user_id'), 'user_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_embeddings_user_id'), table_name='user_embeddings')
    op.drop_index(op.f('ix_user_embeddings_id'), table_name='user_embeddings')
    op.drop_table('user_embeddings')
    # ### end Alembic commands ###
