"""fix travel_time_cache schema

Revision ID: b7cf1f5d39df
Revises: 356aa271c199
Create Date: 2026-02-19 07:18:19.494890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7cf1f5d39df'
down_revision: Union[str, None] = '356aa271c199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_time_cache', sa.Column('origin_hash', sa.String(length=16), nullable=False))
    op.add_column('travel_time_cache', sa.Column('time_bucket', sa.String(length=30), nullable=False))
    op.add_column('travel_time_cache', sa.Column('travel_minutes', sa.Float(), nullable=False))
    op.add_column('travel_time_cache', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_travel_time_cache_origin_hash'), 'travel_time_cache', ['origin_hash'], unique=False)
    op.create_unique_constraint('uq_travel_time_cache', 'travel_time_cache', ['origin_hash', 'venue_id', 'mode', 'time_bucket'])
    op.drop_column('travel_time_cache', 'origin_lng')
    op.drop_column('travel_time_cache', 'distance_meters')
    op.drop_column('travel_time_cache', 'origin_lat')
    op.drop_column('travel_time_cache', 'travel_time_seconds')
    op.drop_column('travel_time_cache', 'fetched_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_time_cache', sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('travel_time_cache', sa.Column('travel_time_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('travel_time_cache', sa.Column('origin_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('travel_time_cache', sa.Column('distance_meters', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('travel_time_cache', sa.Column('origin_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_travel_time_cache', 'travel_time_cache', type_='unique')
    op.drop_index(op.f('ix_travel_time_cache_origin_hash'), table_name='travel_time_cache')
    op.drop_column('travel_time_cache', 'last_checked_at')
    op.drop_column('travel_time_cache', 'travel_minutes')
    op.drop_column('travel_time_cache', 'time_bucket')
    op.drop_column('travel_time_cache', 'origin_hash')
    # ### end Alembic commands ###
