"""add_social_connections_and_signals

Revision ID: d9130dac8367
Revises: 0002_user_profiles
Create Date: 2026-02-22 13:04:59.135407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9130dac8367'
down_revision: Union[str, None] = '0002_user_profiles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_social_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'spotify', name='social_platform_enum'), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_user_id', sa.String(length=120), nullable=True),
    sa.Column('platform_username', sa.String(length=120), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_social_connections_user_id'), 'user_social_connections', ['user_id'], unique=False)
    op.create_table('user_social_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('signal_type', sa.String(length=80), nullable=False),
    sa.Column('signal_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_social_signals_signal_type'), 'user_social_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_user_social_signals_user_id'), 'user_social_signals', ['user_id'], unique=False)
    op.drop_index('ix_bookings_booked_date', table_name='bookings')
    op.drop_index('ix_bookings_match_id', table_name='bookings')
    op.drop_index('ix_bookings_slot_id', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_matches_status', table_name='matches')
    op.drop_index('ix_matches_user_a_id', table_name='matches')
    op.drop_index('ix_matches_user_b_id', table_name='matches')
    op.drop_table('matches')
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('matches_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_b_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='matchstatus'), server_default=sa.text("'pending'::matchstatus"), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['venue_slots.id'], name='matches_slot_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], name='matches_user_a_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], name='matches_user_b_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='matches_venue_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='matches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_matches_user_b_id', 'matches', ['user_b_id'], unique=False)
    op.create_index('ix_matches_user_a_id', 'matches', ['user_a_id'], unique=False)
    op.create_index('ix_matches_status', 'matches', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'cancelled', 'refunded', name='bookingstatus'), server_default=sa.text("'pending'::bookingstatus"), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('deposit_amount_pence', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=False),
    sa.Column('booked_date', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('booked_time', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='bookings_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['venue_slots.id'], name='bookings_slot_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='bookings_venue_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='bookings_pkey')
    )
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_slot_id', 'bookings', ['slot_id'], unique=False)
    op.create_index('ix_bookings_match_id', 'bookings', ['match_id'], unique=False)
    op.create_index('ix_bookings_booked_date', 'bookings', ['booked_date'], unique=False)
    op.drop_index(op.f('ix_user_social_signals_user_id'), table_name='user_social_signals')
    op.drop_index(op.f('ix_user_social_signals_signal_type'), table_name='user_social_signals')
    op.drop_table('user_social_signals')
    op.drop_index(op.f('ix_user_social_connections_user_id'), table_name='user_social_connections')
    op.drop_table('user_social_connections')
    # ### end Alembic commands ###
